import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  taskbar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '28px',
    backgroundColor: 'var(--ButtonFace)',
    borderTop: '1px solid var(--ButtonHilight)',
    borderLeft: '1px solid var(--ButtonHilight)',
    borderRight: '1px solid var(--ButtonHilight)',
    borderBottom: '1px solid var(--ButtonShadow)',
    display: 'flex',
    alignItems: 'center',
    padding: '0 4px',
    zIndex: 5000,
  },
  divider: {
    width: '1px',
    height: '22px',
    backgroundColor: 'var(--ButtonShadow)',
    borderRight: '1px solid var(--ButtonHilight)',
    margin: '0 4px',
  },
  startButton: {
    height: '22px',
    borderStyle: 'solid',
    borderWidth: '1px',
    borderColor: 'var(--ButtonLight) var(--ButtonShadow) var(--ButtonShadow) var(--ButtonLight)',
    boxShadow: '1px 1px 0px black',
    backgroundColor: 'var(--ButtonFace)',
    display: 'flex',
    alignItems: 'center',
    padding: '0 6px',
    marginRight: '4px',
    fontWeight: 'bold',
  },
  startIcon: {
    width: '16px',
    height: '16px',
    marginRight: '4px',
  },
  divider: {
    height: '100%',
    width: '2px',
    borderLeft: '1px solid #808080',
    borderRight: '1px solid #fff',
    margin: '0 4px',
  },
  tasks: {
    flexGrow: 1,
  },
  tray: {
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    border: '2px inset #fff',
    padding: '0 4px',
  },
  time: {
    fontSize: '12px',
  },
});
