import * as stylex from '@stylexjs/stylex';

export const styles = stylex.create({
  window: {
    position: 'absolute',
    backgroundColor: 'var(--ButtonFace)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderTopColor: 'var(--ButtonLight)',
    borderLeftColor: 'var(--ButtonLight)',
    borderRightColor: 'var(--ButtonHilight)',
    borderBottomColor: 'var(--ButtonHilight)',
    boxShadow: '1px 1px 0px 1px black',
    display: 'flex',
    flexDirection: 'column',
  },
  titleBar: {
    backgroundColor: 'var(--InactiveTitle)',
    color: 'var(--InactiveTitleText)',
    padding: '2px 4px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontWeight: 'bold',
    cursor: 'move',
  },
  activeTitleBar: {
    backgroundColor: 'var(--ActiveTitle)',
    color: 'var(--ActiveTitleText)',
  },
  title: {
    flexGrow: 1,
  },
  titleBarButtons: {
    display: 'flex',
  },
  titleBarButton: {
    backgroundColor: 'var(--ButtonFace)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderTopColor: 'var(--ButtonLight)',
    borderLeftColor: 'var(--ButtonLight)',
    borderRightColor: 'var(--ButtonHilight)',
    borderBottomColor: 'var(--ButtonHilight)',
    boxShadow: '1px 1px 0px black',
    width: '16px',
    height: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    padding: 0,
    marginLeft: '2px',
  },
  closeButton: {
    backgroundColor: 'var(--ButtonFace)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderTopColor: 'var(--ButtonLight)',
    borderLeftColor: 'var(--ButtonLight)',
    borderRightColor: 'var(--ButtonHilight)',
    borderBottomColor: 'var(--ButtonHilight)',
    boxShadow: '1px 1px 0px black',
    width: '16px',
    height: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    padding: 0,
    marginLeft: '2px',
  },
  content: {
    flexGrow: 1,
    padding: '4px',
    backgroundColor: 'var(--Window)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderTopColor: 'var(--ButtonDkShadow)',
    borderLeftColor: 'var(--ButtonDkShadow)',
    borderRightColor: 'var(--ButtonShadow)',
    borderBottomColor: 'var(--ButtonShadow)',
    margin: '2px',
    boxShadow: 'inset 1px 1px 0px var(--ButtonHilight)',
  },
});
